macro(get_all_cpps result cur_dir)
    file(GLOB_RECURSE allcpp ${cur_dir}/*.cpp)
    set(file_list "")
    foreach(cppfile ${allcpp})
        list(APPEND file_list ${cppfile})
    endforeach()
    set(${result} ${file_list})
endmacro()

macro(get_sub_dirs result cur_dir)
    file(GLOB children RELATIVE ${cur_dir} ${cur_dir}/*)
    set(dir_list "")
    foreach(child ${children})
        if(IS_DIRECTORY ${cur_dir}/${child})
            list(APPEND dir_list ${child})
        endif()
    endforeach()
    set(${result} ${dir_list})
endmacro()

macro(print_list lst)
    foreach(element ${lst})
        message(${element})
    endforeach()
endmacro()