# TODO: make it compile recursively
all:
	g++ load_csv.cpp build_index.cpp main.cpp load_record.cpp load_index.cpp search.cpp components/utils/utils.cpp components/reader/reader.cpp components/writter/writter.cpp -o ngram -std=c++17 -Wall -Wno-unused-variable
clean:
	rm -f *.o *.exe